# Generated by Django 5.2.8 on 2026-01-12 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_cartmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartmodel',
            name='pimage',
            field=models.ImageField(default='wall.jpg', upload_to='cart_product'),
        ),
    ]
